### ISSUE TITLE
Tests!!

### ISSUE THREAD

**Issue by Julien00859** [pallas/pyllhttp#1]
Hello there,

I'm going to be that guy :p Could you add a bunch of unittests and maybe a quick benchmark? A file named `tests.py` is much much trustworthy than a sample.

Thank you for the binding! I'm looking forward to play with it!

**Comment by pallas** [comment]
The llhttp project actually has a significant number of unit tests and a performance test already. This binding is relatively straightforward, although I'm happy to take any PRs that allow it to use the upstream tests.
